### ISSUE TITLE
Directory lock issue

### ISSUE THREAD

**Issue by Nostang3** [datawhores/OF-Scraper#154]
Windows 11. Installed via pip. Been happening on the last 4 or 5 versions. Running a 5800x if that makes a difference. 

```
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\multiprocess\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\multiprocess\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 237, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 336, in process_dicts_split
    setDirectoriesDate()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 871, in setDirectoriesDate
    with dir_lock:
```

**Comment by datawhores** [comment]
Yeah I pushed a fix for this 
For some reason it hasn't shown up previously

**Comment by datawhores** [comment]
I pushed a fix for this

**Comment by Nostang3** [comment]
I'm notorious for finding bugs. Also, it's still happening on 3.0.8.

`Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\multiprocess\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\multiprocess\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 237, in process_dict_starter
    asyncio.run(process_dicts_split(username,model_id,ele,log,p_logqueue_,pipe_))
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 336, in process_dicts_split
    setDirectoriesDate()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 872, in setDirectoriesDate
    with dir_lock:`

**Comment by datawhores** [comment]
I think my initial test was too short
I was able to trigger the error on a subsequent longer test

I changed how this is handle in version 3.0.9 
so I hope that is able to fix the issue

**Comment by Nostang3** [comment]
I'm now getting a new error. The script continues on but I don't think it's downloading anything. 

` [filters.dupefilter:51]  Removing duplicate media                                                                filters.py:51 [filters.posts_type_filter:84]  filtering Media to images,audios,videos                                          filters.py:84Exception in thread Thread-66 (queue_process):
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-67 (queue_process):
Exception in thread Thread-68 (queue_process):
Traceback (most recent call last):
    self.run()
Exception in thread Thread-69 (queue_process):
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
    self._target(*self._args, **self._kwargs)
    self.run()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self.run()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 210, in
queue_process
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
    media_type, num_bytes_downloaded,total_size = result
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 210, in
queue_process
    self._target(*self._args, **self._kwargs)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 210, in
queue_process
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 210, in
queue_process
ValueError: not enough values to unpack (expected 3, got 0)
    media_type, num_bytes_downloaded,total_size = result
    media_type, num_bytes_downloaded,total_size = result
    media_type, num_bytes_downloaded,total_size = result
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 0)
ValueError: not enough values to unpack (expected 3, got 0)
ValueError: not enough values to unpack (expected 3, got 0)
Exception in thread Thread-70 (queue_process):
Traceback (most recent call last):
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\XXXXX\AppData\Local\Programs\Python\Python311\Lib\site-packages\ofscraper\utils\download.py", line 210, in
queue_process
    media_type, num_bytes_downloaded,total_size = result
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

**Comment by Nostang3** [comment]
Update: On 3.10 I was able to successfully download everything without error. Thanks for the quick fixes.
