### ISSUE TITLE
AttributeError: 'str' object has no attribute 'is_dir'

### ISSUE THREAD

**Issue by ResidentSpaceDragon** [datawhores/OF-Scraper#87]
Getting this error on the latest while trying to use --auth and --config
Both the config and the auth are in seperate folders in the ofscraper .config folder
ofscraper runs fine without --auth or --config being specified manually

Command
```
ofscraper -u model --auth auth-b --config config-b -o purchased -p debug
```

```
DEBUG    Namespace(version='2.5', log='OFF', discord='OFF', output='DEBUG', config='config-b', auth='auth-b', start.py:11
         username={'model'}, excluded_username=set(), daemon=None, original=False, dupe=False,
         posts=['Purchased'], letter_count=False, action=None, skip_timed=None, filter='.*',
         scrape_paid=False, no_cache=False, account_type=None, renewal=None, sub_status=None,
         before=None, after=None, sort='name', desc=False, users_first=False, command=None)
```
```
TRACEBACK 'str' object has no attribute 'is_dir'                                                  scraper.py:354
TRACEBACK Traceback (most recent call last):                                                      scraper.py:355
            File
          "/home/user/.local/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line
          336, in main
              scrapper()
            File
          "/home/user/.local/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line
          374, in scrapper
              check_auth()
            File
          "/home/user/.local/lib/python3.10/site-packages/ofscraper/commands/scraper.py", line
          280, in check_auth
              headers = auth.make_headers(auth.read_auth())
            File "/home/user/.local/lib/python3.10/site-packages/ofscraper/utils/auth.py", line
          32, in read_auth
              authFile=paths.get_auth_file()
            File "/home/user/.local/lib/python3.10/site-packages/ofscraper/utils/paths.py",
          line 244, in get_auth_file
              if auth.is_dir():
          AttributeError: 'str' object has no attribute 'is_dir'
```

**Comment by datawhores** [comment]
Fixed

**Comment by ResidentSpaceDragon** [comment]
git cloning the repo and moving the ofscraper folder to the site-packages folder and still having the same error when using the above command
